set_pollen_severity:
  mode: single
  alias: Set Pollen Severity
  description: >-
    Configures the air purifier's mode based on pollen severity.
    This is a value between 1-10, and intends to be better than "auto" mode
    for pollen (since the sensor can't detect it).

    If value == 0, the automation will be disabled.

    The air purifier has four fan levels (4 == MAX), and will correspond to
    the severity levels in the following fashion:

       1. Auto mode.
       2. Level 2 for 15 minutes once an hour.
       3. Level 2 for 15 minutes twice an hour.
       4. Level 2.
       5. Level 3 for 15 minutes once an hour.
       6. Level 3 for 15 minutes twice an hour.
       7. Level 3.
       8. Level 4 for 15 minutes once an hour.
       9. Level 4 for 15 minutes twice an hour.
      10. Level 4.

  fields:
    severity:
      name: Severity
      description: 0 is disabled. 10 is death.
      selector:
        number:
          min: 0
          max: 10

    delta:
      name: Increase By
      default: 1
      selector:
        number:
          min: -10
          max: 10

  sequence:
    # If value explicitly set.
    - if:
        - condition: template
          value_template: "{{ severity | default('') | length > 0}}"
      then:
        - service: saver.set_variable
          data:
            name: pollen_severity
            value: "{{ severity }}"

        - stop:

    # Lower bound.
    - if:
        - condition: template
          value_template: "{{ saver_variable('pollen_severity') | default(0, true) | int + delta | default(0, true) <= 0 }}"
      then:
        - service: saver.set_variable
          data:
            name: pollen_severity
            value: 0

        - stop:

    # Upper bound.
    - if:
        - condition: template
          value_template: "{{ saver_variable('pollen_severity') | default(0, true) | int + delta | default(0, true) >= 10 }}"
      then:
        - service: saver.set_variable
          data:
            name: pollen_severity
            value: 10

        - stop:

    - service: saver.set_variable
      data:
        name: pollen_severity
        value: "{{ saver_variable('pollen_severity') | default(0, true) | int + delta | default(0, true) }}"

    - service: script.handle_pollen_severity
      data:
        device: fan.vital_200s
        severity: "{{ saver_variable('pollen_severity') }}"

