purify_air:
  mode: single
  alias: Purify Air
  description: >-
    Increase the air purifier strength for a set duration.

  fields:
    device:
      name: Device
      required: True
      selector:
        entity:
          filter:
            - domain: "fan"

    # NOTE: This is limited to the firmware, because it will round any more
    # granular percentage to these overall values.
    strength:
      name: Strength
      description: Fan speed.
      default: 3
      selector:
        number:
          min: 1
          max: 4

    duration:
      name: Duration
      description: >-
        Configures how long the fan should be on, before it turns off by itself.

      selector:
        duration: {}

  variables:
    # We expect this value to be set on manual mode.
    # If this value is not set, it will default to "auto" preset.
    current_state: "{{ state_attr('fan.vital_200s', 'percentage') }}"

  sequence:
    - service: fan.set_percentage
      data:
        percentage: "{{ strength * 25 }}"
      target:
        entity_id: "{{ device }}"

    - delay:
        hours: "{{ duration.hours | default(0, true) }}"
        minutes: "{{ duration.minutes | default(0, true) }}"
        seconds: "{{ duration.seconds | default(0, true) }}"

    - if:
        # Make sure that we didn't terminate early by manually changing the
        # state ourselves.
        - condition: template
          value_template: "{{ state_attr('fan.vital_200s', 'percentage') == strength * 25 }}"
      then:
        # Restore to previous state.
        - if:
            - condition: template
              value_template: "{{ current_state == None }}"
          then:
            - service: fan.set_preset_mode
              data:
                preset_mode: auto
              target:
                entity_id: "{{ device }}"
          else:
            - service: fan.set_percentage
              data:
                percentage: "{{ current_state }}"
              target:
                entity_id: "{{ device }}"

