# Mark a task as done.
# For more information, see
# https://developer.todoist.com/api/v1/#tag/Tasks/operation/close_task_api_v1_tasks__task_id__close_post
#
# Example:
#   - action: rest_command.todoist_close_task
#     data:
#       task_id: "123"

url: "https://api.todoist.com/api/v1/tasks/{{ task_id }}/close"
method: POST
headers:
  Authorization: !secret todoist_authz_header
