# Problem: The TV is connected to the Base Soundbar by HDMI CEC. This means,
# when the speaker is turned on, the TV is also turned on. And that means the
# TV stays on when we want to send music through the soundbar only.

id: "bose-tv-isolator"
alias: "Bose TV: Keep TV Off"
description: Keep the TV turned off while playing music through Bose Soundbar.

mode: restart

trigger:
  - platform: state
    entity_id: "media_player.lg_webos_smart_tv"
    to: "on"

condition:
  - not:
      - condition: state
        entity_id: input_number.bose_tv_state
        state: "0.0"

action:
  - service: webostv.command
    data:
      entity_id: media_player.lg_webos_smart_tv
      command: "com.webos.service.tvpower/power/turnOffScreen"
