

id: "bose-tv-enqueue-reset"
alias: "Bose TV: Enqueue Reset"
description: >-
  Counter-part to `automation.bose_tv_isolator`; attempts to turn off
  automation based on sane heuristics.

mode: restart

trigger:
  # When it is set back to "TV" mode...
  - platform: state
    entity_id: "media_player.bose_tv"
    attribute: source
    to: "PRODUCT"
  
  # Or when the speaker is turned off...
  - platform: state
    entity_id: "media_player.bose_tv"
    attribute: source
    to: null

condition:
  - condition: state
    entity_id: input_boolean.lg_tv_prevent_wakeup
    state: "on"

action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.lg_tv_one_more_sleep
