# This automation allows us to trigger a living room clean via voice.

id: "clean-living-room"
mode: single
alias: Voice-Activated Living Room Clean
description: >-
  Cleans the living room on voice command.

trigger:
  - platform: conversation
    command: clean the living room

condition: []

action:
  # NOTE: We manage the vacuum settings for each room within the Roborock
  # application itself.

  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - repeat: 1
          segments:
            # This corresponds to the dining area and living room.
            - 20
            - 24

    target:
      entity_id: vacuum.roborock_s7

