# The IKEA STYRBAR Switch is a useful tactile tool that essentially allows
# configurable, arbitrary API commands on a Zigbee network. It has four buttons,
# and 12 event listeners (each button has press, hold, release).

id: "ikea-switch-manager"
alias: IKEA Switch Manager
description: Action to take when the IKEA Switch's buttons are pressed.

# Each button is independent of each other, and state is outsourced to the underlying
# scripts. As such, we can have parallel request handling.
#
# Also, for some reason, "single" does not work.
mode: parallel

# For more information, see https://www.zigbee2mqtt.io/devices/E2001_E2002.html
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Button

condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action != '' }}"

action:
  - variables:
      # This configures how long the music should be playing, before it fades out.
      sleep_time_minutes: 30

      # This is especially useful when performing traces, since we can see the
      # value used to perform conditional processing.
      action: "{{ trigger.payload_json.action }}"

  # Control a night light, with auto-sleep functionality.
  - if:
      - condition: template
        value_template: "{{ action == 'on' }}"
    then:
      - service: script.light_on
        data:
          device: light.wiz
          brightness: 10
          duration:
            hours: 1

  # If we accidentally turn on the light, it's nice to have an option to turn it
  # off again.
  - if:
      - condition: template
        value_template: "{{ action == 'brightness_move_up' }}"
    then:
      - service: script.light_off
        data:
          device: light.wiz

  # Play music.
  - if:
      - condition: template
        value_template: "{{ action == 'off' }}"
    then:
      - service: script.playlist_start
        data:
          target: media_player.home_theater
          playlist: "Soundcloud"
          duration: "{{ sleep_time_minutes }}"
          volume_max: 0.3
          volume_min: 0.2

  # Stop music
  - if:
      - condition: template
        value_template: "{{ action == 'brightness_move_down' }}"
    then:
      - service: script.playlist_stop
        data:
          target: media_player.home_theater

  # NOTE: Unfortunately, we need to catch this on button press (rather than
  # being independent to actual usage) because I can't get status requests to
  # work over MQTT.
  - if:
      - condition: template
        value_template: "{{ trigger.payload_json.battery <= 10 }}"
    then:
      - service: notify.pockets_inc
        data:
          target: "#chores"
          message: Change the IKEA Switch's battery.
          data:
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: The *IKEA Switch* needs its battery changed.
                    It is currently on *{{ trigger.payload_json.battery}}%*.

