mode: single
alias: "Recurring Chores"
description: >-
  Adds TODO item for recurring chores.

# NOTE: HomeAssistant does not support scheduling things any longer than a
# daily basis. Consequently, we implement a poor man's cron job by kicking
# it off 10AM every day, and using the switch statement below to figure out
# which chores should be added to the chores list.
#
# This method avoids having multiple different automation files for a similar
# chore handler.
trigger:
  - platform: time
    at: "10:00:00"

action:
  - service: script.recurring_chores
    data:
      today: "{{ now().strftime('%Y-%m-%d') }}"
      channel: "#chores"
      add_task: true

