# This automation allows us to control the vacuum via voice.
#
# NOTE: We manage the vacuum settings for each room within the Roborock
# application itself. While this means you can't get rid of the application, it also means
# you don't have to redesign a UI to support that.
#
# NOTE: See https://www.home-assistant.io/integrations/roborock/#how-can-i-clean-a-specific-room
# for more details on how to get room -> segment id mapping.

id: "voice-vacuum"
mode: single
alias: Voice-Activated Vacuum
description: >-
  Teach the vacuum to understand spoken instructions.

trigger:
  - platform: conversation
    command:
      - clean the {location}

      # Help the bad STT model
      - queen the {location}

condition: []

action:
  - service: script.handle_roborock_profile
    data:
      device: "vacuum.roborock_s3"
      profile: "{{ trigger.slots.location }}"

    # TODO: How does the script return an error?
    #default:
      #- set_conversation_response: "Clean the {{ trigger.slots.location }} yourself."
