# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_list automations
script: !include_dir_list scripts
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    # Allow Nginx Proxy Manager to redirect requests to homeassistant.
    #
    # NOTE: Currently uncertain how these IPs change. Subnet masks are
    # permitted, but I'm uncertain the IP range that may be dynamically
    # allocated.
    #
    # Consider improving this when we have more details.
    - 172.30.33.3

logger:
  default: info

# This is necessary for building triggers off log output.
system_log:
  fire_event: true