# This automation allows us to trigger a bedroom clean via voice.

id: "clean-bedroom"
mode: single
alias: Voice-Activated Bedroom Clean
description: >-
  Cleans the bedroom on voice command.

trigger:
  - platform: conversation
    command: clean the bedroom

condition: []

action:
  # NOTE: We manage the vacuum settings for each room within the Roborock
  # application itself.

  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - repeat: 1
          segments:
            # This corresponds to the dining area.
            #
            # See https://www.home-assistant.io/integrations/roborock/#how-can-i-clean-a-specific-room
            # for more details.
            - 16

    target:
      entity_id: vacuum.roborock_s7

