# This automation allows us to trigger a kitchen clean via voice.

id: "kitchen-clean"
mode: single
alias: Voice-Activated Kitchen Clean
description: >-
  Cleans the kitchen on voice command.

trigger:
  - platform: conversation
    command: clean the kitchen

condition: []

action:
  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - repeat: 1
          segments:
            # This corresponds to the kitchen,
            #
            # See https://www.home-assistant.io/integrations/roborock/#how-can-i-clean-a-specific-room
            # for more details.
            - 18
    target:
      entity_id: vacuum.roborock_s7
